project_id = "hvqzzhkxvqmlgavplunj"

[functions.chat]
verify_jwt = false

[functions.firecrawl-search]
verify_jwt = false

[functions.kiwify-webhook]
verify_jwt = false

[functions.explain-metric]
verify_jwt = false
